name: Deploy ui

on:
  push:
    branches:
      - master
      - github-actions
    paths:
      - 'ui/**/*.js'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: npm deploy
        run: |
          cd ui && npm deploy
