name: Deploy ui

on:
  push:
    branches:
      - master
      - github-actions

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build and deploy
        run: |
          cd ui
          npm run build
          npm run deploy
